module.exports.descriptors = [
  "KinderCare",
  "Love very",
  "Little Flower",
  "Sunny",
  "Little Angel",
  "Primrose",
  "Carpe Diem",
  "Kids Corner",
  "Bright Beginning",
  "Sunshine and Smile",
  "Tot Lot",
  "Kids Space",
  "Kids Castle",
  "Carefree",
  "Smart Start",
  "Tree House",
  "Tots and Teddy",
  "Small Miracle",
];

module.exports.places = [
  "Daycare",
  "Preschool",
  "Academy",
  "Adventure Zone",
  "Childcare",
  "Playhouse",
  "Home Care",
  "Playgroup",
  "Start Prep",
  "Prep",
  "Learning Academy",
  "School",
  "Daycare Center",
  "Learning Center",
];
